FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# O código será montado via volume, então não copiamos nada aqui.
# Apenas garantimos que o uvicorn esteja disponível.
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
