FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir poetry

COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.create false && \
    poetry install --no-root

COPY src/ ./src/
COPY main.py .

ENV MLFLOW_TRACKING_URI=sqlite:///mlruns.db \
    MLFLOW_MODEL_NAME=MLP_PyTorch \
    MLFLOW_MODEL_ALIAS=challenger

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
